(() => {
  const grid = document.querySelector('.projects');
  if (!grid || document.querySelector('.site-gallery-card')) return;
  const cases = [
    {id:'sun',no:'06',title:'Sun Ritual',type:'Skincare & SPF visual campaign',text:'Ürün dokusu, kullanım anı ve yaz atmosferini temiz, ferah ve ticari bir görsel dilde buluşturan güneş koruması serisi.',images:4},
    {id:'shoes',no:'07',title:'Soft Steps',type:'Footwear editorial',text:'Ayna, silüet ve doğal materyallerle tasarlanan sade ama premium ayakkabı anlatısı.',images:2},
    {id:'avatar',no:'08',title:'AI Avatar Studio',type:'Brand-ready digital humans',text:'Markanızın tonuna göre gerçekçi AI avatarlar: yaş, stil, dil, yüz ifadesi ve kampanya karakteri ihtiyaçlara göre kurgulanır.',images:6,avatar:true},
    {id:'kids',no:'09',title:'Little Stories — Ali & Asaf',type:'Kids storytelling system',text:'Ali & Asaf karakter dünyasını Little Stories anlatısına dahil eden; aile, oyun, hareket ve duyguyu tutarlı bir çocuk hikâyesinde birleştiren görsel sistem.',media:['assets/site-showcase/kids-1.webp','assets/site-showcase/kids-2.webp','assets/showcase/kids-1.webp','assets/showcase/kids-2.webp','assets/showcase/kids-3.webp','assets/site-showcase/kids-4.webp']},
    {id:'motion',no:'10',title:'Motion Studies',type:'AI video & moving image',text:'Görsel dünyayı yalnızca tek karede değil; hareket, ritim ve kısa video anlatısında da sürdüren seçili hareketli üretimler.',videos:8}
  ];
  grid.insertAdjacentHTML('beforeend',cases.map(c=>`<button class="showcase-card site-gallery-card ${c.id==='motion'?'motion-card':''}" data-site-case="${c.id}" style="background-image:linear-gradient(0deg,rgba(4,12,7,.7),rgba(4,12,7,.05)),url('assets/site-showcase/${c.id==='motion'?'sun-1':c.id+'-1'}.webp')"><span>${c.no}</span><div><small>${c.type}</small><strong>${c.title}</strong><em>${c.id==='motion'?'Videoları izle ↗':'Vaka çalışmasını aç ↗'}</em></div></button>`).join(''));
  const dialog=document.createElement('dialog');dialog.className='site-gallery-dialog';document.body.append(dialog);
  function imageMarkup(c){const media=c.media||Array.from({length:c.images},(_,i)=>`assets/site-showcase/${c.id}-${i+1}.webp`);return media.map((src,i)=>`<img src="${src}" alt="${c.title} görseli ${i+1}" loading="lazy">`).join('')}
  function open(c){const media=c.videos?Array.from({length:c.videos},(_,i)=>`<video controls preload="metadata" playsinline src="assets/site-showcase/motion-${i+1}.mp4"></video>`).join(''):imageMarkup(c);const avatar=c.avatar?'<div class="avatar-note"><b>Detay kontrolü</b><span>Göz, cilt dokusu, burun, kulak, ağız, saç/hijab çizgisi, el ve takı detayları; karakterin inandırıcılığını artırmak için tek tek ele alınır.</span></div>':'';dialog.innerHTML=`<button class="site-close" aria-label="Kapat">×</button><header><p>${c.no} — ${c.type}</p><h2>${c.title}</h2><span>PORTFOLYO KONSEPT ÇALIŞMASI</span><p>${c.text}</p></header>${avatar}<div class="site-media ${c.videos?'video-wall':''}">${media}</div>`;dialog.showModal();dialog.querySelector('.site-close').onclick=()=>dialog.close()}
  grid.addEventListener('click',e=>{const b=e.target.closest('[data-site-case]');if(b)open(cases.find(c=>c.id===b.dataset.siteCase))});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  const style=document.createElement('style');style.textContent=`.site-gallery-card{background-position:center;background-size:cover,contain;background-repeat:no-repeat}.motion-card{background-blend-mode:normal;position:relative}.motion-card:after{content:'▶';position:absolute;right:1.5rem;top:1.5rem;width:2.5rem;height:2.5rem;display:grid;place-items:center;border:1px solid #fff;border-radius:50%;color:#fff}.site-gallery-dialog{width:min(1120px,95vw);border:0;background:#f4f0e7;color:#071a11;padding:0}.site-gallery-dialog::backdrop{background:#071a11dd;backdrop-filter:blur(8px)}.site-gallery-dialog header{background:#0b2918;color:#fff9ee;padding:5rem 7% 3rem}.site-gallery-dialog header p:first-child{font:.65rem 'DM Mono';letter-spacing:.1em;color:#d5ad33}.site-gallery-dialog h2{font:500 clamp(3rem,8vw,7rem)/.84 'Playfair Display';letter-spacing:-.07em;margin:1rem 0}.site-gallery-dialog header span{font:.61rem 'DM Mono';letter-spacing:.07em;border:1px solid #fff7;padding:.45rem .6rem}.site-gallery-dialog header p:last-child{max-width:42rem;line-height:1.6}.site-close{position:sticky;float:right;top:1rem;right:1rem;z-index:5;width:2.5rem;height:2.5rem;border:0;border-radius:50%;background:#f4f0e7;color:#071a11;font-size:1.5rem;cursor:pointer}.site-media{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem;padding:1rem}.site-media img{width:100%;height:auto;max-height:none;object-fit:contain;background:#071a11}.site-media img:first-child{grid-column:span 2;max-height:none}.site-media video{width:100%;height:100%;min-height:13rem;max-height:42rem;object-fit:cover;background:#071a11}.avatar-note{margin:2rem 7% 0;padding:1rem;border-left:3px solid #d5ad33;display:grid;grid-template-columns:10rem 1fr;gap:1rem;font-size:.85rem;line-height:1.5}.video-wall video:first-child{grid-column:span 2;min-height:26rem}@media(max-width:760px){.site-gallery-dialog{width:100vw;max-width:100vw;min-height:100vh}.site-gallery-dialog header{padding:4rem 7% 2.5rem}.site-media{grid-template-columns:1fr}.site-media img,.site-media img:first-child,.video-wall video,.video-wall video:first-child{grid-column:auto;min-height:14rem}.avatar-note{display:block}.avatar-note span{display:block;margin-top:.5rem}}`;document.head.append(style);
})();
